# Generated by Django 6.1 on 2026-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('sickness', models.CharField(max_length=128)),
            ],
        ),
    ]
