# Generated by Django 6.1 on 2026-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=64)),
                ('specialization', models.CharField(max_length=128)),
                ('doctors', models.ManyToManyField(related_name='doctors', to='information.information')),
            ],
        ),
    ]
