# Generated by Django 6.1 on 2026-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='filenumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
