# Generated by Django 6.1 on 2026-09-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_filenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='patients.dieseases'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients with this ill+', to='patients.dieseases'),
        ),
    ]
